repos/Task23BugLess/Controllers/GuestController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task23BugLess.Helpers;
using Task23BugLess.Models;

namespace Task23.Controllers
{
    public class GuestController : Controller
    {
        private static List<Feedback> _feedbacks;
        static GuestController() 
        {
            _feedbacks = FeedbackModel.GetFeedbacks();
        }
        public ActionResult Index()
        {
            return View(_feedbacks);
        }
        [HttpGet]
        public ActionResult Feedback(int id)
        {
            var blogFeedback = _feedbacks.Where(feedback => feedback.BlogId == id);
            ViewBag.BlogId = id;

            return View(blogFeedback);
        }
        [HttpPost]
        public RedirectToRouteResult Feedback(Feedback feedback) 
        {
            if (ModelState.IsValid) 
            {
                _feedbacks.Add(feedback);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

repos/Task23BugLess/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task23BugLess.Helpers;
using Task23BugLess.Models;

namespace Task23.Controllers
{
    public class HomeController : Controller
    {
        private static List<Blog> _blogs;
        static HomeController()
        {
            _blogs = BlogModel.GetBlogs();
        }
        public ActionResult Index()
        {
            return View(_blogs);
        }

    }
}

repos/Task23BugLess/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task23BugLess.Helpers;
using Task23BugLess.Models;

namespace Task23BugLess.Controllers
{
    public class QuestionnaireController : Controller
    {
        [ActionName("New")]
        [HttpGet]
        public ActionResult CreateNewPost()
        {
            return View();
        }
        [ActionName("New")]
        [HttpPost]
        public RedirectToRouteResult CreateNewPost(Blog blog)
        {
            if (ModelState.IsValid)
            {
                AddBlog(blog);
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("New", "Questionnaire");
        }
        private void AddBlog(Blog blog)
        {
            var blogs = BlogModel.GetBlogs();

            blogs.Add(new Blog() 
            { 
                //fekalis
                Id = blogs.Where(b => b.Id == blog.Id).Any() ? blogs.Last().Id: blog.Id, 
                AuthorName = blog.AuthorName, 
                Content = blog.Content, 
                CreationTime = blog.CreationTime, 
                Header = blog.Header 
            });

        }
    }
}

repos/Task23BugLess/Views/Guest/Feedback.cshtml
@model System.Collections.Generic.IEnumerable<Task23BugLess.Helpers.Feedback>

<div class="feedback-container">
    @foreach (var feedback in Model)
    {
        <div class="feedback">
            <h2>@feedback.Content</h2>
            <b><i>Author: @feedback.AuthorName</i></b>
            <h5>Date: @feedback.CreationTime</h5>
            <h5>Id: @feedback.BlogId</h5>
        </div>
    }
</div>
<div class="feedback-form">
    <h2>Feedback Form</h2>
    @using (Html.BeginForm("Feedback", "Guest", FormMethod.Post))
    {
        <input class="form-control" type="hidden" value="@ViewBag.BlogId" name="blogId" />
        <p for="authorName">Enter author name: </p><input class="form-control" type="text" id="authorName" name="authorName" />
        <p for="content">Enter feedback text: </p><input class="form-control" type="text" id="content" name="content" />
        <p for="feedbackContent">Creation time: </p><input class="form-control" type="text" id="feedbackCreationTime" name="feedbackCreationTime" value="@DateTime.Now" disabled />
        <p><input class="btn btn-default" type="submit" value="send" /></p>
    }
</div>

repos/Task23BugLess/Views/Guest/Index.cshtml
@model IEnumerable<Task23BugLess.Helpers.Feedback>
    @{
        ViewBag.Title = "Index";
    }


    <div class="feedback-container">
        <h1 class="feedback-container-header">Feedback History</h1>
        @foreach (var feedback in Model)
        {
            <div class="feedback">
                <h2>@feedback.Content</h2>
                <b><i>Author: @feedback.AuthorName</i></b>
                <h5>Date: @feedback.CreationTime</h5>
                <h3>@feedback.BlogId</h3>
            </div>
        }
    </div>

repos/Task23BugLess/Views/Home/Index.cshtml
@model System.Collections.Generic.IEnumerable<Task23BugLess.Helpers.Blog>

<div>
    @foreach(var blog in Model) 
    {
        <div class="blog">
            <h2>@blog.Header</h2>
            <p>
                @blog.Content
            </p>
            <b><i>Author: @blog.AuthorName</i></b>
            <h5>Date: @blog.CreationTime</h5>
            @Html.ActionLink("See comments", "Feedback", "Guest", new { id = blog.Id }, new {@class = "blog-link" })
        </div>
    }
</div>

repos/Task23BugLess/Views/Questionnaire/New.cshtml
@using Task23BugLess.Helpers

@{
    ViewBag.Title = "New";
}
@{
    List<string> creationPostList = new List<string>()
    {
        "Your post should not contain text that incites hatred",
        "Post text must not contain obscene language ",
        "Author name should be real name",
        "Post should have 3 links to trusted sources"
    };

    List<string> selectOptions = new List<string>()
    {
        "First option",
        "Second option",
        "Third option",
        "Fourth option",
        "Five option"
    };
 }
    <div class="form-container">
        <h2>Rules for creating form</h2>
        @Html.CreateList(creationPostList, HelperType.Ol)
        @Html.CreateSelect(selectOptions, "test-options")

        @using (Html.BeginForm("New", "Questionnaire", FormMethod.Post, new { @class = "questionnaire-form" }))
        {
            <p>Enter header: </p>
            <input class="form-control" type="text" id="header" name="header" />
            <p>Enter content: </p>
            <input class="form-control" type="text" id="content" name="content" />
            <p>Enter author name: </p>
            <input class="form-control" type="text" id="authorName" name="authorName" />
            <p>Creation time: </p><input class="form-control" type="text" id="creationTime" name="creationTime" value="@DateTime.Now" disabled/>
            <p><input class="btn btn-default" type="submit" value="send" /></p>
        }
    </div>

repos/Task23BugLess/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header main">

                <a href="/" class="navbar-brand"><i class="fa fa-fw fa-book"></i>Library</a>
                @*@Html.ActionLink("Library", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="col-md-9">
                @RenderBody()

            </div>
            <div class="col-md-3">
                <div class="jumbotron">
                    <ul class="jumbotron-menu">
                        <li>
                            @Html.ActionLink("Main", "Index", "Home", new { area = "" }, new { @class = "jumbotron-menu-item" })
                        </li>
                        <li>
                            @Html.ActionLink("Guest", "Index", "Guest", new { area = "" }, new { @class = "jumbotron-menu-item" })
                        </li>
                        <li>
                            @Html.ActionLink("Questionnaire", "New", "Questionnaire", new { area = "" }, new { @class = "jumbotron-menu-item" })
                        </li>
                    </ul>
                </div>

            </div>
        </div>

        <hr />
        <footer class="navbar-fixed-bottom">
            <div class="container">
                <p>&copy; Yevhenii Hrytsiuk topkokos1337@gmail.com - My ASP.NET Application</p>
            </div>
        </footer>

    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</body>
</html>